# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPods-Lab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPods-Lab
  pod 'Alamofire'
  pod 'SnapKit'
  

  target 'CocoaPods-LabTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
